npm run android:apk
> nextpos-order@0.1.0 android:apk
> cd android && c

diff --git a/android/gradlew b/android/gradlew
--- a/android/gradlew
+++ b/android/gradlew
@@ -1,6 +1,8 @@
-#!/usr/bin/env sh
+#!/bin/sh
 
-# Standard Gradle wrapper script for Unix
+# Standard Gradle Wrapper Script for Unix
+# Fixed argument parsing to prevent "-Xmx64m" error
+
 APP_NAME="Gradle"
 APP_BASE_NAME=`basename "$0"`
 
@@ -19,9 +21,10 @@ die () {
 }
 
 # OS specific support (must be 'true' or 'false').
-cygwin=false;
-msys=false;
-darwin=false;
+cygwin=false
+msys=false
+darwin=false
+nonstop=false
 case "`uname`" in
   CYGWIN* )
     cygwin=true
@@ -31,6 +34,9 @@ case "`uname`" in
     ;;
   MINGW* )
     msys=true
+    ;;
+  NONSTOP* )
+    nonstop=true
     ;;
 esac
 
@@ -59,22 +65,31 @@ location of your Java installation."
 fi
 
 # Increase the maximum file descriptors if we can.
-if [ "$cygwin" = "false" -a "$msys" = "false" -a "$darwin" = "false" ] ; then
+if [ "$cygwin" = "false" -a "$msys" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
     MAX_FD_LIMIT=`ulimit -H -n`
     if [ $? -eq 0 ] ; then
-        if [ "$MAX_FD_LIMIT" = "unlimited" ] ; then
-            MAX_FD_LIMIT=$MAX_FD_LIMIT
+        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
+            MAX_FD="$MAX_FD_LIMIT"
         fi
-        ulimit -n $MAX_FD_LIMIT
+        ulimit -n $MAX_FD
+        if [ $? -ne 0 ] ; then
+            warn "Could not set maximum file descriptor limit: $MAX_FD"
+        fi
+    else
+        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
     fi
 fi
 
 # For Cygwin, switch paths to Windows format before running java
 if $cygwin ; then
-    APP_HOME=`cygpath --mixed "$APP_HOME"`
-    CLASSPATH=`cygpath --mixed "$CLASSPATH"`
-    JAVACMD=`cygpath --mixed "$JAVACMD"`
+    APP_HOME=`cygpath --path --windows "$APP_HOME"`
+    JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
+    CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
 fi
 
-# Execute Gradle
-exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "-Dorg.gradle.appname=$APP_BASE_NAME" -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
+# Collect all arguments for the java command, following the shell's rules for
+# word splitting and globbing.
+eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$@"
+
+exec "$JAVACMD" "$@"
+    
